[workspace]
resolver = "2"
members = ["lib", "sdk"]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(target_os, values("solana"))',
] }


[workspace.dependencies]
shank = "0.4.2"
spl-token-interface = "2.0.0"
spl-token-2022-interface = "2.1.0"
spl-associated-token-account-interface = "2.0.0"
solana-program = "3"
borsh = { version = "1", features = ["derive"] }
bytemuck = "1.7.2"
num_enum = "=0.5.11"
thiserror = "1.0.38"
solana-security-txt = "1.1.0"
static_assertions = "=1.1.0"
solana-invoke = "0.5"

anyhow = "1.0.66"
solana-account = "3"
solana-account-decoder = "3"
solana-account-info = "3"
solana-compute-budget-interface = "3"
solana-program-test = "3"
solana-logger = "3"
solana-keypair = "3"
solana-program-pack = "3"
solana-pubkey = { version = "3", features = ["curve25519"] }
solana-rpc-client = "3"
solana-rpc-client-api = "3"
solana-signer = "3"
solana-transaction = "3"
tokio = "1.28.0"

nondet = { version = "0.6.1", package = "cvlr-nondet" }
cvt = { version = "0.6.1", package = "cvlr-asserts" }
early-panic = { version = "0.6.1", package = "cvlr-early-panic" }
cvt-macros = { version = "0.6.1", package = "cvlr-macros" }
calltrace = { version = "0.6.1", package = "cvlr-log" }
solana_cvt = { version = "0.5.0", package = "cvlr-solana" }
hook_macro = { version = "0.6.1", package = "cvlr-hook" }
vectors = { version = "0.4.0", package = "cvlr-vectors" }
cvlr = "0.6.1"

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release]
codegen-units = 1
lto = "fat"
overflow-checks = true
strip = "debuginfo"

[profile.release.build-override]
codegen-units = 1
incremental = false
opt-level = 3
strip = "debuginfo"

# Test with release settings so CU usage is accurately measured.
[profile.test]
lto = "fat"
opt-level = 3
debug = false
codegen-units = 1
overflow-checks = true
strip = "debuginfo"
