[package]
name = "manifest-sdk"
version = "0.1.0"
edition = "2024"

[features]
default = []
test = []

[dependencies]
hypertree = { path = "../lib" }
bytemuck.workspace = true
const-crypto = "0.3.0"
solana-pubkey = { version = ">=3", features = ["curve25519"] }
solana-program-error = "3"
thiserror = "2.0"
spl-token-2022-interface = "2"
spl-token-interface = "2"
solana-account-info = "3"
solana-sdk-ids = "3"

[lints]
workspace = true
